services:
  - type: web
    name: endoscopia-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: ~20.0.0
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
